version: '3'
services:
  database:
    image: 'postgres'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_MULTIPLE_DATABASES=main,test
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - database-data7:/var/lib/postgresql/data
      - ./docker/pg:/docker-entrypoint-initdb.d
    networks:
      - apbp-network
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - 6380:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  database-data7:

networks:
  apbp-network:
